FROM debian:bookworm

RUN apt-get update && apt-get install -y apache2 build-essential wget git patch

RUN wget http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz \
    && tar xzf bash-4.3.tar.gz

RUN wget http://ftp.gnu.org/gnu/bash/bash-4.3-patches/bash43-025 -O bash43-025 \
    && cd bash-4.3 \
    && (patch -p0 < ../bash43-025 || true) \
    && ./configure && make && make install

RUN ln -sf /usr/local/bin/bash /bin/bash
RUN bash --version

RUN a2enmod cgi

RUN echo -e '#!/bin/bash\necho "Content-type: text/html"\necho ""\necho "Serveur en ligne (patch CVE-2014-6271 applique)."' \
    > /usr/lib/cgi-bin/test.sh \
    && chmod +x /usr/lib/cgi-bin/test.sh

RUN echo -e '#!/bin/bash\necho "Content-type: text/plain"\necho ""\n/bin/bash --version' \
    > /usr/lib/cgi-bin/version.sh \
    && chmod +x /usr/lib/cgi-bin/version.sh

RUN git clone https://github.com/iamelboi/Univ-tp-shellshock /tmp/data \
    && cp -r /tmp/data/site/. /var/www/html \
    && rm -rf /tmp/data

EXPOSE 80
CMD ["apachectl", "-D", "FOREGROUND"]
